In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [3]:
df_preprocessed = pd.read_csv('2 - Absenteeism_preprocessing_output.csv')
df_preprocessed

Reason 1  Reason 2  Reason 3  Reason 4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
5           0         0         0         1            7                4   
6           0         0         0         1            7                4   
7           0         0         0         1            7                4   
8           0         0         1         0            7                0   
9           0         0         0         1            7                0   
10          1         0         0         0            7                0   
11          1         0         0         0            7                1   
12          1         0         0         0            7                2   
13          1         0         0         0            7                2   
14          0         0         0         1            7                2   
15          1         0         0         0            7                4   
16          0         0         0         1            7                4   
17          0         0         1         0            7                0   
18          1         0         0         0            7                3   
19          0         0         0         1            8                2   
20          1         0         0         0            8                2   
21          1         0         0         0            8                0   
22          1         0         0         0            8                0   
23          0         0         0         1            8                4   
24          0         0         1         0            8                0   
25          0         0         0         1            8                0   
26          0         0         0         1            8                1   
27          0         0         0         1            8                2   
28          0         0         1         0            8                2   
29          0         0         0         1            8                4   
30          0         0         1         0            8                0   
31          0         0         1         0            8                3   
32          0         0         0         1            8                3   
33          0         0         1         0            8                0   
34          0         0         0         1            8                0   
35          0         0         0         1            8                0   
36          0         0         0         1            8                1   
37          1         0         0         0            8                3   
38          0         0         0         1            8                4   
39          0         0         0         1            8                4   
40          0         0         0         1            9                1   
41          0         0         0         1            9                0   
42          0         0         0         1            9                1   
43          0         0         1         0            9                1   
44          0         0         0         1            9                2   
45          0         0         0         1            9                6   
46          0         0         0         1            9                0   
47          0         0         0         1            9                3   
48          0         0         0         1            9                4   
49          1         0         0         0            9                0   
50          0         0         0         0            9                0   
5

In [4]:
df_preprocessed['Absenteeism Time in Hours'].median()

np.float64(3.0)

In [5]:
targets = np.where(df_preprocessed['Absenteeism Time in Hours'] > df_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
df_preprocessed ['Excessive Absenteeism'] = targets
df_preprocessed

Reason 1  Reason 2  Reason 3  Reason 4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
5           0         0         0         1            7                4   
6           0         0         0         1            7                4   
7           0         0         0         1            7                4   
8           0         0         1         0            7                0   
9           0         0         0         1            7                0   
10          1         0         0         0            7                0   
11          1         0         0         0            7                1   
12          1         0         0         0            7                2   
13          1         0         0         0            7                2   
14          0         0         0         1            7                2   
15          1         0         0         0            7                4   
16          0         0         0         1            7                4   
17          0         0         1         0            7                0   
18          1         0         0         0            7                3   
19          0         0         0         1            8                2   
20          1         0         0         0            8                2   
21          1         0         0         0            8                0   
22          1         0         0         0            8                0   
23          0         0         0         1            8                4   
24          0         0         1         0            8                0   
25          0         0         0         1            8                0   
26          0         0         0         1            8                1   
27          0         0         0         1            8                2   
28          0         0         1         0            8                2   
29          0         0         0         1            8                4   
30          0         0         1         0            8                0   
31          0         0         1         0            8                3   
32          0         0         0         1            8                3   
33          0         0         1         0            8                0   
34          0         0         0         1            8                0   
35          0         0         0         1            8                0   
36          0         0         0         1            8                1   
37          1         0         0         0            8                3   
38          0         0         0         1            8                4   
39          0         0         0         1            8                4   
40          0         0         0         1            9                1   
41          0         0         0         1            9                0   
42          0         0         0         1            9                1   
43          0         0         1         0            9                1   
44          0         0         0         1            9                2   
45          0         0         0         1            9                6   
46          0         0         0         1            9                0   
47          0         0         0         1            9                3   
48          0         0         0         1            9                4   
49          1         0         0         0            9                0   
50          0         0         0         0            9                0   
5

In [7]:
df_with_targets = df_preprocessed.copy()
df_with_targets = df_with_targets.drop(['Absenteeism Time in Hours', 'Day of the Week', 'Distance to Work', 'Daily Work Load Average'], axis = 1)
df_with_targets

Reason 1  Reason 2  Reason 3  Reason 4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
5           0         0         0         1            7   
6           0         0         0         1            7   
7           0         0         0         1            7   
8           0         0         1         0            7   
9           0         0         0         1            7   
10          1         0         0         0            7   
11          1         0         0         0            7   
12          1         0         0         0            7   
13          1         0         0         0            7   
14          0         0         0         1            7   
15          1         0         0         0            7   
16          0         0         0         1            7   
17          0         0         1         0            7   
18          1         0         0         0            7   
19          0         0         0         1            8   
20          1         0         0         0            8   
21          1         0         0         0            8   
22          1         0         0         0            8   
23          0         0         0         1            8   
24          0         0         1         0            8   
25          0         0         0         1            8   
26          0         0         0         1            8   
27          0         0         0         1            8   
28          0         0         1         0            8   
29          0         0         0         1            8   
30          0         0         1         0            8   
31          0         0         1         0            8   
32          0         0         0         1            8   
33          0         0         1         0            8   
34          0         0         0         1            8   
35          0         0         0         1            8   
36          0         0         0         1            8   
37          1         0         0         0            8   
38          0         0         0         1            8   
39          0         0         0         1            8   
40          0         0         0         1            9   
41          0         0         0         1            9   
42          0         0         0         1            9   
43          0         0         1         0            9   
44          0         0         0         1            9   
45          0         0         0         1            9   
46          0         0         0         1            9   
47          0         0         0         1            9   
48          0         0         0         1            9   
49          1         0         0         0            9   
50          0         0         0         0            9   
51          0         0         0         0            9   
52          0         0         0         1            9   
53          0         0         0         1            9   
54          0         0         0         0            9   
55          0         0         0         0            9   
56          0         0         1         0            9   
57          0         0         0         1            9   
58          0         0         0         0            9   
59          0         0         0         1            9   
60          0         0         0         1            9   
61          0         0         0         1            9   
62          0         0         0         1           10   
63          0         0         0         1           10   
64          0         0         0         0           10   
65          0         0         0         1  

In [8]:
targets.sum() / targets.shape[0]

np.float64(0.45571428571428574)

In [9]:
df_with_targets is df_preprocessed

False

In [10]:
unscaled_inputs = df_with_targets.iloc[:,:-1] 
#or df_with_targets.iloc[:0:14] since total columns are 15 and you want last one to cut off, hence also -1.
unscaled_inputs

Reason 1  Reason 2  Reason 3  Reason 4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
5           0         0         0         1            7   
6           0         0         0         1            7   
7           0         0         0         1            7   
8           0         0         1         0            7   
9           0         0         0         1            7   
10          1         0         0         0            7   
11          1         0         0         0            7   
12          1         0         0         0            7   
13          1         0         0         0            7   
14          0         0         0         1            7   
15          1         0         0         0            7   
16          0         0         0         1            7   
17          0         0         1         0            7   
18          1         0         0         0            7   
19          0         0         0         1            8   
20          1         0         0         0            8   
21          1         0         0         0            8   
22          1         0         0         0            8   
23          0         0         0         1            8   
24          0         0         1         0            8   
25          0         0         0         1            8   
26          0         0         0         1            8   
27          0         0         0         1            8   
28          0         0         1         0            8   
29          0         0         0         1            8   
30          0         0         1         0            8   
31          0         0         1         0            8   
32          0         0         0         1            8   
33          0         0         1         0            8   
34          0         0         0         1            8   
35          0         0         0         1            8   
36          0         0         0         1            8   
37          1         0         0         0            8   
38          0         0         0         1            8   
39          0         0         0         1            8   
40          0         0         0         1            9   
41          0         0         0         1            9   
42          0         0         0         1            9   
43          0         0         1         0            9   
44          0         0         0         1            9   
45          0         0         0         1            9   
46          0         0         0         1            9   
47          0         0         0         1            9   
48          0         0         0         1            9   
49          1         0         0         0            9   
50          0         0         0         0            9   
51          0         0         0         0            9   
52          0         0         0         1            9   
53          0         0         0         1            9   
54          0         0         0         0            9   
55          0         0         0         0            9   
56          0         0         1         0            9   
57          0         0         0         1            9   
58          0         0         0         0            9   
59          0         0         0         1            9   
60          0         0         0         1            9   
61          0         0         0         1            9   
62          0         0         0         1           10   
63          0         0         0         1           10   
64          0         0         0         0           10   
65          0         0         0         1  

In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin
absenteeism_scaler = StandardScaler()

In [12]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    def __init__(self, columns):
        self.columns = columns  # The columns to scale
        self.scaler = StandardScaler()  # Internal scaler for the specified columns
        self.mean_ = None  # Mean values after fitting
        self.var_ = None   # Variance values after fitting

    def fit(self, X, y=None):
        # Check if specified columns exist in DataFrame
        if not set(self.columns).issubset(X.columns):
            missing_cols = list(set(self.columns) - set(X.columns))
            raise ValueError(f"The following columns are missing in the DataFrame: {missing_cols}")

        # Fit only on the specified columns
        self.scaler.fit(X[self.columns])
        self.mean_ = self.scaler.mean_
        self.var_ = self.scaler.var_
        return self

    def transform(self, X, y=None):
        # Scale the specified columns, leave the rest unchanged
        X_scaled = X.copy()
        X_scaled[self.columns] = self.scaler.transform(X[self.columns])
        return X_scaled


In [13]:
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [14]:
columns_to_omit = ['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Education']

In [15]:
columns_to_scale = [x for x in unscaled_inputs if x not in columns_to_omit]
columns_to_scale

['Month Value',
 'Transportation Expense',
 'Age',
 'Body Mass Index',
 'Children',
 'Pets']

In [16]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [17]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [18]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [19]:
scaled_inputs

Reason 1  Reason 2  Reason 3  Reason 4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
5           0         0         0         1     0.182726   
6           0         0         0         1     0.182726   
7           0         0         0         1     0.182726   
8           0         0         1         0     0.182726   
9           0         0         0         1     0.182726   
10          1         0         0         0     0.182726   
11          1         0         0         0     0.182726   
12          1         0         0         0     0.182726   
13          1         0         0         0     0.182726   
14          0         0         0         1     0.182726   
15          1         0         0         0     0.182726   
16          0         0         0         1     0.182726   
17          0         0         1         0     0.182726   
18          1         0         0         0     0.182726   
19          0         0         0         1     0.468236   
20          1         0         0         0     0.468236   
21          1         0         0         0     0.468236   
22          1         0         0         0     0.468236   
23          0         0         0         1     0.468236   
24          0         0         1         0     0.468236   
25          0         0         0         1     0.468236   
26          0         0         0         1     0.468236   
27          0         0         0         1     0.468236   
28          0         0         1         0     0.468236   
29          0         0         0         1     0.468236   
30          0         0         1         0     0.468236   
31          0         0         1         0     0.468236   
32          0         0         0         1     0.468236   
33          0         0         1         0     0.468236   
34          0         0         0         1     0.468236   
35          0         0         0         1     0.468236   
36          0         0         0         1     0.468236   
37          1         0         0         0     0.468236   
38          0         0         0         1     0.468236   
39          0         0         0         1     0.468236   
40          0         0         0         1     0.753746   
41          0         0         0         1     0.753746   
42          0         0         0         1     0.753746   
43          0         0         1         0     0.753746   
44          0         0         0         1     0.753746   
45          0         0         0         1     0.753746   
46          0         0         0         1     0.753746   
47          0         0         0         1     0.753746   
48          0         0         0         1     0.753746   
49          1         0         0         0     0.753746   
50          0         0         0         0     0.753746   
51          0         0         0         0     0.753746   
52          0         0         0         1     0.753746   
53          0         0         0         1     0.753746   
54          0         0         0         0     0.753746   
55          0         0         0         0     0.753746   
56          0         0         1         0     0.753746   
57          0         0         0         1     0.753746   
58          0         0         0         0     0.753746   
59          0         0         0         1     0.753746   
60          0         0         0         1     0.753746   
61          0         0         0         1     0.753746   
62          0         0         0         1     1.039256   
63          0         0         0         1     1.039256   
64          0         0         0         0     1.039256   
65          0         0         0         1  

In [20]:
scaled_inputs.shape

(700, 11)

In [21]:
from sklearn.model_selection import train_test_split
train_test_split(scaled_inputs,targets)

[     Reason 1  Reason 2  Reason 3  Reason 4  Month Value  \
 519         0         0         0         1     1.039256   
 412         0         0         0         1    -0.673803   
 300         0         0         0         0     1.039256   
 99          0         0         1         0     1.610276   
 674         0         0         0         1    -0.388293   
 263         1         0         0         0     0.468236   
 408         0         0         0         1    -0.959313   
 524         1         0         0         0     1.039256   
 237         1         0         0         0     0.182726   
 591         0         0         0         1    -1.244823   
 386         0         0         0         1    -1.244823   
 23          0         0         0         1     0.468236   
 152         0         0         0         1    -1.244823   
 81          0         0         0         1     1.324766   
 88          0         0         0         1     1.324766   
 608         0         0

In [22]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs,targets, test_size = 0.2, random_state = 20)

In [23]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [24]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [26]:
reg = LogisticRegression()

In [27]:
reg.fit(x_train, y_train)

LogisticRegression()

In [28]:
reg.score(x_train, y_train)

0.7732142857142857

In [29]:
# Mannually verifying the score
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [30]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [31]:
np.sum(model_outputs == y_train) / y_train.shape[0]

np.float64(0.7732142857142857)

In [32]:
reg.intercept_

array([-1.6469898])

In [33]:
reg.coef_

array([[ 2.80000644,  0.95174778,  3.1140605 ,  0.83835931,  0.15897713,
         0.60513709, -0.16990589,  0.27998236, -0.21017416,  0.34842434,
        -0.27721907]])

In [34]:
# Didn't used scaled_inputs here because scaled_inputs were converted into ndarrays from dataframes which does not include column names/lables
feature_name = unscaled_inputs.columns.values
feature_name

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [35]:
summary_table = pd.DataFrame(columns = ['Feature Names'], data = feature_name)

In [36]:
summary_table['Coefficients'] = np.transpose(reg.coef_)
summary_table                                    

Feature Names  Coefficients
0                 Reason 1      2.800006
1                 Reason 2      0.951748
2                 Reason 3      3.114061
3                 Reason 4      0.838359
4              Month Value      0.158977
5   Transportation Expense      0.605137
6                      Age     -0.169906
7          Body Mass Index      0.279982
8                Education     -0.210174
9                 Children      0.348424
10                    Pets     -0.277219

In [37]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
# Intercept added in the last row, but with 0 Index Number hence sort required
summary_table = summary_table.sort_index()
summary_table

Feature Names  Coefficients
0                Intercept     -1.646990
1                 Reason 1      2.800006
2                 Reason 2      0.951748
3                 Reason 3      3.114061
4                 Reason 4      0.838359
5              Month Value      0.158977
6   Transportation Expense      0.605137
7                      Age     -0.169906
8          Body Mass Index      0.279982
9                Education     -0.210174
10                Children      0.348424
11                    Pets     -0.277219

In [38]:
summary_table['Odds_Ratio'] = np.exp(summary_table.Coefficients)
summary_table

Feature Names  Coefficients  Odds_Ratio
0                Intercept     -1.646990    0.192629
1                 Reason 1      2.800006   16.444753
2                 Reason 2      0.951748    2.590233
3                 Reason 3      3.114061   22.512270
4                 Reason 4      0.838359    2.312570
5              Month Value      0.158977    1.172311
6   Transportation Expense      0.605137    1.831503
7                      Age     -0.169906    0.843744
8          Body Mass Index      0.279982    1.323106
9                Education     -0.210174    0.810443
10                Children      0.348424    1.416833
11                    Pets     -0.277219    0.757888

In [39]:
summary_table.sort_values('Odds_Ratio', ascending=False)

Feature Names  Coefficients  Odds_Ratio
3                 Reason 3      3.114061   22.512270
1                 Reason 1      2.800006   16.444753
2                 Reason 2      0.951748    2.590233
4                 Reason 4      0.838359    2.312570
6   Transportation Expense      0.605137    1.831503
10                Children      0.348424    1.416833
8          Body Mass Index      0.279982    1.323106
5              Month Value      0.158977    1.172311
7                      Age     -0.169906    0.843744
9                Education     -0.210174    0.810443
11                    Pets     -0.277219    0.757888
0                Intercept     -1.646990    0.192629

In [40]:
reg.score(x_test, y_test)

0.75

In [41]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71342516, 0.28657484],
       [0.5873216 , 0.4126784 ],
       [0.44016153, 0.55983847],
       [0.78163061, 0.21836939],
       [0.08407928, 0.91592072],
       [0.3348226 , 0.6651774 ],
       [0.29971206, 0.70028794],
       [0.13112385, 0.86887615],
       [0.78627908, 0.21372092],
       [0.74906578, 0.25093422],
       [0.49395555, 0.50604445],
       [0.22492002, 0.77507998],
       [0.07135527, 0.92864473],
       [0.73173354, 0.26826646],
       [0.30957854, 0.69042146],
       [0.54726422, 0.45273578],
       [0.55051921, 0.44948079],
       [0.53926379, 0.46073621],
       [0.40197149, 0.59802851],
       [0.05365482, 0.94634518],
       [0.70030387, 0.29969613],
       [0.78163061, 0.21836939],
       [0.42028246, 0.57971754],
       [0.42028246, 0.57971754],
       [0.24801464, 0.75198536],
       [0.74567806, 0.25432194],
       [0.51026557, 0.48973443],
       [0.8569309 , 0.1430691 ],
       [0.20365204, 0.79634796],
       [0.78163061, 0.21836939],
       [0.

In [42]:
predicted_proba.shape

(140, 2)

In [43]:
predicted_proba[:,1]

array([0.28657484, 0.4126784 , 0.55983847, 0.21836939, 0.91592072,
       0.6651774 , 0.70028794, 0.86887615, 0.21372092, 0.25093422,
       0.50604445, 0.77507998, 0.92864473, 0.26826646, 0.69042146,
       0.45273578, 0.44948079, 0.46073621, 0.59802851, 0.94634518,
       0.29969613, 0.21836939, 0.57971754, 0.57971754, 0.75198536,
       0.25432194, 0.48973443, 0.1430691 , 0.79634796, 0.21836939,
       0.36947677, 0.67913195, 0.68508325, 0.52870791, 0.21836939,
       0.53505228, 0.22144744, 0.73673169, 0.40500758, 0.60504297,
       0.21072119, 0.45227108, 0.23749326, 0.39847178, 0.82763577,
       0.56771922, 0.69120847, 0.28657484, 0.2192347 , 0.2032712 ,
       0.57634482, 0.32954238, 0.6651774 , 0.26937528, 0.83323682,
       0.43484145, 0.88365871, 0.23125087, 0.33433749, 0.34451397,
       0.69915101, 0.6549938 , 0.29244583, 0.79186052, 0.20752232,
       0.26838009, 0.08710411, 0.22144744, 0.73215219, 0.30536526,
       0.22144744, 0.2900789 , 0.90443841, 0.46065771, 0.60175

In [44]:
import pickle

In [45]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [46]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)